22-Jan-04 17:46:56 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75ae84b0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-04 17:47:01 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b06650>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-04 17:47:06 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b06a90>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-04 17:47:11 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b06ed0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-04 17:47:16 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b06e70>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-04 17:47:21 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b068f0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-04 17:47:26 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b06670>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-04 17:47:31 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75ae8df0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-04 17:47:36 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a32330>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-04 17:47:41 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a32770>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-04 17:47:46 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a32bb0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-04 17:47:51 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75ae8d50>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-04 17:47:56 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b06570>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-04 17:48:01 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b06990>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-04 17:48:06 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b06ed0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-04 17:48:11 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a32a50>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-04 17:48:16 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a32630>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-04 17:48:21 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a322f0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-04 17:48:26 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a32ff0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-04 17:48:54 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Read timed out. (read timeout=5)
22-Jan-05 12:50:11 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b06ef0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:54:27 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b01ff0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:54:32 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b1f5f0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:54:37 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b1fa30>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:54:42 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b1fe70>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:54:47 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b1fe90>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:54:57 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b1f230>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:55:02 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75af1b30>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:55:07 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b01410>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:55:12 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4c2d0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:55:17 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4c710>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:55:22 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4cb50>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:55:28 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b015b0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:55:33 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b01e10>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:56:10 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b1fc90>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:56:30 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75b1f790>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
22-Jan-05 12:56:45 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b1fa50>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:57:01 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4c950>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:57:06 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4c470>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:57:11 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4c2d0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:57:26 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4cf90>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:57:31 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b1f190>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:57:36 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b1f5d0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:57:41 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b01e90>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:57:46 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b012b0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:57:51 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4c5f0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:57:56 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4c690>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:58:01 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4ccf0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:58:06 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b01490>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:58:19 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Read timed out. (read timeout=5)
22-Jan-05 12:58:38 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4c550>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 12:58:45 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4c270>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:00:30 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a62150>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:00:36 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a62750>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:00:56 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75a62b90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
22-Jan-05 13:01:11 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a62ad0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:01:16 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4cf50>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:01:21 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4c570>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:01:26 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4c870>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:01:31 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b01f70>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:01:46 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b01f90>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:02:06 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a62af0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:02:26 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75a62750>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
22-Jan-05 13:02:31 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a62610>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:02:51 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75a62f90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
22-Jan-05 13:02:57 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b01610>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:03:02 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4cc30>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:03:12 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4cb90>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:03:17 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4ced0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:03:22 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a62250>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:03:27 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a62f10>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:03:32 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a62d70>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:03:37 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4ca30>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:03:42 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4c910>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:03:47 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4ca10>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:03:52 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b01f70>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:03:57 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b01fd0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:04:02 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a628b0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:06:34 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a62390>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:06:39 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a62e30>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:06:50 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a62110>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:06:55 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a62390>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:07:00 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a62c50>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:07:05 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4c2d0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:07:10 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4c710>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:07:15 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4cb50>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:07:44 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4cbd0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:08:04 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75a4caf0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
22-Jan-05 13:11:34 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Read timed out. (read timeout=5)
22-Jan-05 13:13:56 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4cb90>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:14:01 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b01690>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:14:06 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b01610>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:14:11 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a66310>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:14:16 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a66750>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:14:24 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a666d0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:14:29 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b016f0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:14:34 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4cff0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:14:39 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4cbb0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:14:44 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4c9b0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:14:49 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a66730>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:14:54 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a660f0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:14:59 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a66f90>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:15:04 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a668f0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:15:09 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a66390>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:15:14 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4c390>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:15:19 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4cfd0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:15:25 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4c790>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:15:30 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b01670>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:15:58 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b01c70>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:16:03 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a693f0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:16:08 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4c930>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:16:13 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4c0b0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:16:18 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4cc90>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:16:24 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a66570>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:16:29 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a66210>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:16:34 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a66b10>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:16:39 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a69150>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:16:44 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4ce10>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:16:49 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4cb10>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:16:54 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a4c330>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:16:59 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a66130>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:17:04 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a665f0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:17:09 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a667f0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:17:14 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b015f0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:17:19 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75b01fd0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:17:24 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a664b0>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
22-Jan-05 13:17:29 - error = HTTPConnectionPool(host='connect-srvc.monit.tech', port=80): Max retries exceeded with url: /api/Getvideorequest/?hubid=29 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75a66370>, 'Connection to connect-srvc.monit.tech timed out. (connect timeout=5)'))
